name = "telegraph-image"
compatibility_date = "2023-12-01"
main = "src/index.ts"

[env.dev.vars]
API_HOST = "https://telegraph.mingming.dev"

[env.prod.vars]
API_HOST = "https://telegra.ph"

[site]
bucket = "./src"